### ISSUE TITLE
switch is sometimes broken

### ISSUE THREAD

**Issue by cdsmith** [AndrasKovacs/flatparse#12] opened 2021-09-29 18:32 UTC
The follow use of `switch` seems to be broken.  It recognizes everything except "E" or "W"

``` haskell
$(switch [| case _ of
  "eastward" -> pure ()
  "Eastward" -> pure ()
  "EASTWARD" -> pure ()
  "westward" -> pure ()
  "Westward" -> pure ()
  "WESTWARD" -> pure ()
  "east" -> pure ()
  "East" -> pure ()
  "EAST" -> pure ()
  "west" -> pure ()
  "West" -> pure ()
  "WEST" -> pure ()
  "e" -> pure ()
  "E" -> pure ()
  "w" -> pure ()
  "W" -> pure ()
  "in" -> pure ()
  "In" -> pure ()
  "IN" -> pure ()
  "out" -> pure ()
  "Out" -> pure ()
  "OUT" -> pure ()
```

**Comment by fryguybob** [comment] 2021-09-29 19:09
Small program that reproduces this problem:

```haskell
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE OverloadedStrings #-}
import qualified FlatParse.Basic as FP
import qualified Data.ByteString as BS
import qualified Data.ByteString.Char8 as C8

parse = $(FP.switch [| case _ of
  "eastward" -> pure ()
  "Eastward" -> pure ()
  "EASTWARD" -> pure ()
  "east" -> pure ()
  "East" -> pure ()
  "e" -> pure ()
  "E" -> pure ()
  |])

test :: String -> FP.Result () ()
test s = FP.runParser parse (C8.pack s)

main = do
    mapM_ (print . test) $
       [ "Eastward"
       , "eastward"
       , "East"
       , "east"
       , "e"
       , "E"
       ]
```

Running:

```
*Main> :main
OK () ""
OK () ""
OK () ""
OK () ""
OK () ""
Fail
```

If you comment out the `EASTWARD` line `E` parses as expected.

**Comment by AndrasKovacs** [comment] 2021-09-29 19:11
Thanks guys! I also narrowed it down:

```
test1 = $(switch [| case _ of
  "Eac" -> pure ()
  "EAc" -> pure ()
  "E"   -> pure ()
   |])
```
I'm also getting an ambiguous type error for the following:

```
test2 = (switch [| case _ of
  "Ea" -> pure ()
  "EA" -> pure ()
  "E"  -> pure ()
   |])
```
The type error seems to be because of a unused branch in the code output. Probably related to the other error.

**Comment by AndrasKovacs** [comment] 2021-09-29 21:51
I believe I fixed it in 82fb6ace15f84b6678670ae2403f41d71cb962e9. Of course it'd be preferable to have tests as well. Note that I recently updated to ghc 9, now `flatparse` only builds under that; if anyone would like to have 8.8 and 8.10 support I'll add it.

**Comment by cdsmith** [comment] 2021-09-29 23:43
Thnaks for the fix.  We're currently evaluating flatparse with GHC 8.6.5 for an internal code base.  Hoping to update to 8.10 in the near future, but that's a non-trivial task in a setting with lots of developers and custom build tools.  It'll likely be quite a while before our code is migrated to GHC 9.  If it's not feasible to add support for 8.6, then we'll be stuck on an old version for a bit.

**Comment by AndrasKovacs** [comment] 2021-09-30 06:44
I'm closing this one. Added #13 for GHC support, I'll try to support down to 8.6.5, it shouldn't be too difficult.

**Closed by AndrasKovacs** 2021-09-30 06:44 UTC
